# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

workspace 'PhotoSaver.xcworkspace'

target 'PhotoSaver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoSaver
  #pod 'Gallery', path: './LocalPods/Gallery'
  #pod 'Lightbox', path: './LocalPods/Lightbox'
  #pod 'Cache', path: './LocalPods/Cache'
  #pod 'Imaginary', path: './LocalPods/Imaginary'
  pod 'Hue', path: './LocalPods/Hue'
  pod 'SVProgressHUD', path: './LocalPods/SVProgressHUD'
  pod 'PureLayout', '~> 3.1.4'
  pod 'SwiftEventBus', :tag => '3.0.1', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
  pod 'FSPagerView'
  pod 'ATGMediaBrowser', '~> 1.0'
  pod 'CyaneaOctopus'
  #pod 'RealmSwift'
  pod 'GRDB.swift'
  pod 'XCGLogger', '~> 6.1.0'
  #pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  pod 'FLEX', '~> 2.0'
  pod 'WechatOpenSDK'
  #https://github.com/xmartlabs/XLSwiftKit
  #pod 'XLSwiftKit'
  #pod 'SwiftLint'
  pod 'Eureka'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GesturePassword'
  pod 'DataCompression'
  
  pod 'ImageIOSwift_F2', :path => '/Users/sunyx/temp/ImageIOSwift/'
  pod 'SwipeSelectingCollectionView2'
  pod 'SwiftPagingTabView', :path => '/Users/sunyx/workspace/ios/SwiftPagingTabView/'
  pod 'SwiftBaseBootstrap', :path => '/Users/sunyx/workspace/ios/SwiftBaseBootstrap/'
end

target 'UIViewsSample' do
    project 'UIViewsSample/UIViewsSample.xcodeproj'
    
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for UIViewSample
    pod 'PureLayout', '~> 3.1.4'
    
end
